#!/usr/bin/env bash
# Boots the Codex CLI as an Obot hosted agent.
#
# Same shape as the Claude Code image: everything is read from
# /etc/obot/agent.json, which carries absolute endpoints and their credentials.

set -euo pipefail
# shellcheck source=../lib/obot-agent.sh
source /usr/local/lib/obot-agent.sh

obot::require_config

# Codex keeps its sessions and history under ~/.codex, which is part of the
# image; without this they are lost on every restart. The generated config below
# is rewritten each boot regardless.
obot::persist "$HOME/.codex" dir

config_dir="$HOME/.codex"
mkdir -p "$config_dir"
config="$config_dir/config.toml"

{
  echo '# Generated by Obot at container start. Edits are lost on restart.'
} >"$config"

# Codex speaks the OpenAI wire protocol.
if IFS=$'\t' read -r model base_url api_key < <(obot::model openai-responses); then
  # The key goes through the environment rather than into the file, so the
  # credential is not left on disk in a config Codex may print.
  export OPENAI_API_KEY="$api_key"

  # Codex treats base_url as an OpenAI-style base and appends only /responses,
  # so it wants the /v1 that the config leaves off -- the config reports the
  # root of Obot's proxy, and which version a client asks for belongs to the
  # protocol that client speaks. Conditional so the image also works against an
  # Obot old enough to still report the version itself.
  case "$base_url" in
    */v1) ;;
    *) base_url="${base_url%/}/v1" ;;
  esac

  {
    echo 'model_provider = "obot"'
    printf 'model = "%s"\n' "$model"
    echo
    echo '[model_providers.obot]'
    echo 'name = "Obot"'
    printf 'base_url = "%s"\n' "$base_url"
    echo 'env_key = "OPENAI_API_KEY"'
    # Codex removed the chat-completions wire protocol; it speaks the Responses
    # API now, which Obot's OpenAI proxy forwards.
    echo 'wire_api = "responses"'
  } >>"$config"
  obot::log "using model $model"
elif [ -z "${OPENAI_API_KEY:-}" ]; then
  obot::fail "this agent has no model speaking the OpenAI Responses API, which is the only protocol Codex uses. Grant it an OpenAI-backed model, or set OPENAI_API_KEY in the agent's environment."
fi

server_count=0
while IFS=$'\t' read -r name url auth; do
  [ -n "$url" ] || continue
  {
    echo
    printf '[mcp_servers.%s]\n' "$name"
    printf 'url = "%s"\n' "$url"
    [ -n "$auth" ] && printf 'http_headers = { Authorization = "%s" }\n' "$auth"
  } >>"$config"
  server_count=$((server_count + 1))
done < <(obot::config '.mcpServers[]? | [(.name // .id), .url, (.headers.Authorization // "")] | @tsv')

chmod 600 "$config"
obot::log "configured $server_count MCP server(s)"

# Codex reaches MCP servers over streamable HTTP only through the Rust MCP
# client, which is still behind a flag.
if [ "$server_count" -gt 0 ]; then
  export CODEX_EXPERIMENTAL_USE_RMCP_CLIENT=1
fi

# Codex has no skills concept of its own, so they are linked somewhere an agent
# can find and read them.
obot::link_skills "$(obot::workspace)/.obot/skills"

# Two statements, not `cd "$(obot::clone_source)"`: obot::fail inside a command
# substitution exits only the subshell, so a failed clone would leave `cd ""` --
# a silent no-op -- and the agent would start in the wrong directory with no
# repository. Assigning first makes set -e see the failure.
workdir="$(obot::clone_source)"
cd "$workdir"

exec codex "$@"
